### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by lohfu** [zouhir/eslint-config-standard-preact#1]
Hi, the eslint-config-standard-jsx has been updated to v4.

Are you able to update your package to use the latest deps?

**Comment by zouhir** [comment]
Hey, sure I'll update and release shortly. please expect a release in ~12hours.

**Comment by zouhir** [comment]
Please feel free to update to latest package v1.1.1! Just got released.

**Comment by lohfu** [comment]
@zouhir excellent, thanks for quick action!
